theme = "fallout"

[editor]
color-modes = true
gutters     = ["line-numbers", "spacer", "diff"]

[editor.file-picker]
hidden =  false

[keys.normal]
X = "extend_line_above"

[keys.normal."\\"]
r = ":config-reload"

[keys.normal."\\".g]
n = ":set gutters []"
d = ':set gutters ["diff"]'
a = ':set gutters ["line-numbers", "diff"]'


[keys.normal.space.n]
t   = ":lsp-workspace-command today"
n   = ":lsp-workspace-command tomorrow"
p   = ":lsp-workspace-command yesterday"
i   = ":open Inbox.md"

[keys.normal.space.b]
b = "buffer_picker"
d = ":buffer-close"
s = ":write"

[keys.normal.space.i]
d = ":insert-output zsh -ic fancy_date"

[keys.normal.space.t]
x   = ["extend_to_line_bounds", ":pipe sed 's/\\[.\\]/[x]/'"]
">" = ["extend_to_line_bounds", ":pipe sed 's/\\[.\\]/[>]/'"]
" " = ["extend_to_line_bounds", ":pipe sed 's/\\[.\\]/[ ]/'"]
c   = ["extend_to_line_bounds", ":pipe sed -E 's/^[[:space:]]*(- (\\[.\\] )?)?//'"]
l   = ["extend_to_line_bounds", ":pipe sed -E 's/^[[:space:]]*(- (\\[.\\] )?)?/- /'"]
t   = ["extend_to_line_bounds", ":pipe sed -E 's/^[[:space:]]*(- (\\[.\\] )?)?/- [ ] /'"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
