backend: file
check_updates: true
export:
    ical:
        file_name: tock_export.ics
file:
    path: /Users/boek/.tock.txt
language: eng
last_update_check: 2026-06-20T07:15:18.611781-07:00
sqlite:
    path: /Users/boek/.tock.db
theme:
    faint: '#2e402a'
    highlight: '#7bcf6b'
    name: custom
    primary: '#95ff80'
    secondary: '#6ebf5d'
    sub_text: '#487041'
    tag: '#62a058'
    tag_colors:
        personal: '#6ebf5d'
        urgent: '#ff5555'
        warning: '#d4b84f'
        work: '#95ff80'
    text: '#95ff80'
time_format: "24"
timewarrior:
    use_tock_tag_colors: false
    use_tock_tag_colors_calendar: false
    use_tock_tag_colors_top_projects: false
    use_tock_tag_colors_weekly_activity: false
working_hours:
    enabled: false
    stop_at: ""
    weekdays: mon,tue,wed,thu,fri
