[helpers]

[default]
depends = []

[default.files]
"zshrc"          = "~/.zshrc"
"config/zellij"  = "~/.config/zellij"
"config/ghostty" = "~/.config/ghostty"

[default.variables]

[settings]
default_target_type = "automatic"
